# Generated by Django 5.0.3 on 2024-03-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prototype", "0002_alter_problem_statement"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
    ]
