# Generated by Django 5.0.3 on 2024-04-11 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prototype", "0003_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
