# Generated by Django 5.0.3 on 2024-04-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prototype", "0004_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
